

services:
  db:
    image: postgres:latest
    container_name: messenger_db
    restart: always
    environment:
      POSTGRES_DB: messenger
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: messenger_web
    restart: always
    depends_on:
      - db
    ports:
      - "5431:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - DATABASE_URL=postgresql://user:password@db:5432/messenger
    volumes:
      - .:/app

volumes:
  pg_data:

